formats = [
    "TXT",
    "PDF",
    "FB2",
    "EPUB",
    "LIT",
    "MOBI",
    "RTF",
    "DJV",
    "DJVU",
    "AZW",
    "AZW3",
]

languages = [
    "abkhazian",
    "afar",
    "afrikaans",
    "akan",
    "albanian",
    "amharic",
    "aragonese",
    "assamese",
    "avaric",
    "avestan",
    "aymara",
    "bambara",
    "bashkir",
    "basque",
    "belarusian",
    "berber",
    "bislama",
    "bosnian",
    "breton",
    "bulgarian",
    "burmese",
    "catalan",
    "central_khmer",
    "chamorro",
    "chechen",
    "chichewa",
    "church_slavic",
    "chuvash",
    "cornish",
    "corsican",
    "cree",
    "crimean",
    "croatian",
    "czech",
    "danish",
    "divehi",
    "dzongkha",
    "esperanto",
    "estonian",
    "ewe",
    "faroese",
    "fijian",
    "finnish",
    "fulah",
    "gaelic",
    "galician",
    "ganda",
    "guarani",
    "gujarati",
    "haitian",
    "hausa",
    "hebrew",
    "herero",
    "hiri_motu",
    "hungarian",
    "icelandic",
    "ido",
    "igbo",
    "indigenous",
    "interlingua",
    "inuktitut",
    "inupiaq",
    "irish",
    "javanese",
    "kalaallisut",
    "kannada",
    "kanuri",
    "kashmiri",
    "kazakh",
    "kikuyu",
    "kinyarwanda",
    "kirghiz",
    "komi",
    "kongo",
    "kuanyama",
    "kurdish",
    "lao",
    "latin",
    "latvian",
    "limburgan",
    "lingala",
    "lithuanian",
    "katanga",
    "luxembourgish",
    "macedonian",
    "malagasy",
    "malayalam",
    "maltese",
    "manx",
    "maori",
    "marathi",
    "marshallese",
    "moldavian",
    "mongolian",
    "nauru",
    "navajo",
    "ndonga",
    "nepali",
    "north_ndebele",
    "northern_sami",
    "norwegian",
    "norwegian_bokmal",
    "norwegian_nynorsk",
    "occidental",
    "occitan",
    "odia",
    "ojibwa",
    "oromo",
    "ossetian",
    "pali",
    "persian",
    "punjabi",
    "quechua",
    "romanian",
    "romansh",
    "rundi",
    "samoan",
    "sango",
    "sanskrit",
    "sardinian",
    "shona",
    "sichuan_yi",
    "sindhi",
    "sinhala",
    "slovak",
    "slovenian",
    "somali",
    "south_ndebele",
    "southern_sotho",
    "sundanese",
    "swahili",
    "swati",
    "swedish",
    "tagalog",
    "tahitian",
    "tajik",
    "tamil",
    "tatar",
    "tibetan",
    "tigrinya",
    "tonga",
    "tsonga",
    "tswana",
    "turkmen",
    "twi",
    "uighur",
    "uzbek",
    "venda",
    "volapuk",
    "walloon",
    "welsh",
    "western_frisian",
    "wolof",
    "xhosa",
    "yiddish",
    "yoruba",
    "zhuang",
    "zulu",
]

languages_s = {
    "en": "english",
    "ru": "russian",
    "de": "german",
    "es": "spanish",
    "nl": "dutch",
    "fr": "french",
    "it": "italian",
    "pt": "portuguese",
    "zh": "chinese",
    "pl": "polish",
    "uk": "ukrainian",
    "bg": "bulgarian",
    "el": "greek",
    "ro": "romanian",
    "mo": "moldavian",
    "tr": "turkish",
    "fa": "persian",
    "ar": "arabic",
    "ja": "japanese",
    "sv": "swedish",
    "hu": "hungarian",
    "sr": "serbian",
    "la": "latin",
    "hr": "croatian",
    "cs": "czech",
    "kk": "kazakh",
    "be": "belarusian",
    "id": "indonesian",
    "ms": "malaysian",
    "lt": "lithuanian",
    "ca": "catalan",
    "fi": "finnish",
    "az": "azerbaijani",
    "ko": "korean",
    "bn": "bengali",
    "eo": "esperanto",
    "hi": "hindi",
    "ur": "urdu",
    "da": "danish",
    "uz": "uzbek",
    "sk": "slovak",
    "no": "norwegian",
    "vi": "vietnamese",
    "Indig.": "indigenous",
    "ba": "bashkir",
    "mr": "marathi",
    "ky": "kirghiz",
    "tg": "tajik",
    "tt": "tatar",
    "sq": "albanian",
    "so": "somali",
    "is": "icelandic",
    "mn": "mongolian",
    "lv": "latvian",
    "ka": "georgian",
    "sa": "sanskrit",
    "he": "hebrew",
    "sl": "slovenian",
    "ml": "malayalam",
    "af": "afrikaans",
    "ne": "nepali",
    "si": "sinhala",
    "ber": "berber",
    "hy": "armenian",
    "cri": "crimean",
    "ta": "tamil",
    "or": "odia",
    "sw": "swahili",
    "gu": "gujarati",
    "te": "telugu",
    "kn": "kannada",
    "et": "estonian",
    "th": "thai",
    "ch": "chamorro",
    "gl": "galician",
    "ab": "abkhazian",
    "aa": "afar",
    "ak": "akan",
    "am": "amharic",
    "an": "aragonese",
    "as": "assamese",
    "av": "avaric",
    "ae": "avestan",
    "ay": "aymara",
    "bm": "bambara",
    "eu": "basque",
    "bi": "bislama",
    "bs": "bosnian",
    "br": "breton",
    "my": "burmese",
    "ce": "chechen",
    "ny": "chichewa",
    "cu": "church_slavic",
    "cv": "chuvash",
    "kw": "cornish",
    "co": "corsican",
    "cr": "cree",
    "dv": "divehi",
    "dz": "dzongkha",
    "ee": "ewe",
    "fo": "faroese",
    "fj": "fijian",
    "fy": "western_frisian",
    "ff": "fulah",
    "gd": "gaelic",
    "lg": "ganda",
    "kl": "kalaallisut",
    "gn": "guarani",
    "ht": "haitian",
    "ha": "hausa",
    "hz": "herero",
    "ho": "hiri_motu",
    "io": "ido",
    "ig": "igbo",
    "ia": "interlingua",
    "ie": "occidental",
    "iu": "inuktitut",
    "ik": "inupiaq",
    "ga": "irish",
    "jv": "javanese",
    "kr": "kanuri",
    "ks": "kashmiri",
    "km": "central_khmer",
    "ki": "kikuyu",
    "rw": "kinyarwanda",
    "kv": "komi",
    "kg": "kongo",
    "kj": "kuanyama",
    "ku": "kurdish",
    "lo": "lao",
    "li": "limburgan",
    "ln": "lingala",
    "lu": "luba-katanga",
    "lb": "luxembourgish",
    "mk": "macedonian",
    "mg": "malagasy",
    "mt": "maltese",
    "gv": "manx",
    "mi": "maori",
    "mh": "marshallese",
    "na": "nauru",
    "nv": "navajo",
    "nd": "north_ndebele",
    "nr": "south_ndebele",
    "ng": "ndonga",
    "nb": "norwegian_bokmal",
    "nn": "norwegian_nynorsk",
    "ii": "sichuan_yi",
    "oc": "occitan",
    "oj": "ojibwa",
    "om": "oromo",
    "os": "ossetian",
    "pi": "pali",
    "ps": "pashto",
    "pa": "punjabi",
    "qu": "quechua",
    "rm": "romansh",
    "rn": "rundi",
    "se": "northern_sami",
    "sm": "samoan",
    "sg": "sango",
    "sc": "sardinian",
    "sn": "shona",
    "sd": "sindhi",
    "st": "southern_sotho",
    "su": "sundanese",
    "ss": "swati",
    "tl": "tagalog",
    "ty": "tahitian",
    "bo": "tibetan",
    "ti": "tigrinya",
    "to": "tonga",
    "ts": "tsonga",
    "tn": "tswana",
    "tk": "turkmen",
    "tw": "twi",
    "ug": "uighur",
    "ve": "venda",
    "vo": "volapuk",
    "wa": "walloon",
    "cy": "welsh",
    "wo": "wolof",
    "xh": "xhosa",
    "yi": "yiddish",
    "yo": "yoruba",
    "za": "zhuang",
    "zu": "zulu",
}

orders = [
    "popular",
    "bestmatch",
    "date",
    "titleA",
    "title",
    "year",
    "filesize",
    "filesizeA",
]
